# This workflow will build the java project then tag the docker image.

name: Java Ecosystem CI.

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Build & Push the image to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: ghcr.io
        repository: certmichelin/javaecosystem/javaecosystem
        tags: latest
        
